#!/bin/bash
#when ssh login,test status of webhosting services and proxy services are running 
#if 3services is not running,start them
#Date:Mon Nov 9 19  ^z50

#CADDY_STATUS1=$(systemctl status caddy |grep Active |awk '{print $3}'|cut -d "(" -f2 |cut -d ")" -f1)
WH_STATUS1=$(systemctl status nginx |grep Active |awk '{print $3}'|cut -d "(" -f2 |cut -d ")" -f1)
if [ "$WH_STATUS1" == "dead" ]; then
	echo "Webhosting service:Nginx is dead,It will be started Now!"
#	systemctl stop {caddy,v2ray,naiveproxy,shadowsocks}
	systemctl start {nginx,xray}
else
#	CADDY_STATUS2=$(systemctl status caddy |grep " - " |awk '{print $4,$5,$6,$7}')
	WH_STATUS2=$(systemctl status nginx |grep " - " |awk '{print $4,$5,$6,$7,$8,$9,$10}')
#	echo $CADDY_STATUS2" is "$CADDY_STATUS1
	echo $WH_STATUS2" is "$WH_STATUS1
fi
