#!/bin/bash
#when ssh login,test status of 3 services which are caddy v2ray and naiveproxy
#if 3services is not running,start them
#Date:Mon Nov 9 19  ^z50

CADDY_STATUS1=$(systemctl status caddy |grep Active |awk '{print $3}'|cut -d "(" -f2 |cut -d ")" -f1)
if [ "$CADDY_STATUS1" == "running" ]; then
	echo "Caddy service is running,It will be stoped Now!"
	systemctl stop {caddy,v2ray,naiveproxy}
else
	CADDY_STATUS2=$(systemctl status caddy |grep " - " |awk '{print $4,$5,$6,$7}')
	echo $CADDY_STATUS2" is "$CADDY_STATUS1
fi
